In [1]:
import torch
import torchvision
from torchvision import transforms
from torchvision import datasets

In [28]:
import numpy as np

In [3]:
train = datasets.MNIST('', train=True,
                       download=False,
                       transform=transforms.Compose([
                           transforms.ToTensor()
                       ]))


test = datasets.MNIST('', train=False,
                       download=False,
                       transform=transforms.Compose([
                           transforms.ToTensor()
                       ]))

In [9]:
print('Num of training samples: ', train.data.shape[0])
print('Num of test samples: ', test.data.shape[0])

Num of training samples:  60000
Num of test samples:  10000


In [10]:
trainset = torch.utils.data.DataLoader(train, batch_size=64, shuffle=True)
testset = torch.utils.data.DataLoader(test, batch_size=64, shuffle=True)

In [11]:
img_shape = train.data[0].shape[0]
img_shape

28

In [12]:
num_classes = len(train.classes)
num_classes

10

In [26]:
trainset.dataset.data

60000

In [45]:
train_targets = []
test_targets = []

#### One-hot encoding the targets

In [46]:
for target in trainset.dataset.targets:
    train_targets.append(torch.eye(num_classes)[target])

In [47]:
train_targets[:10]

[tensor([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]),
 tensor([1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 tensor([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]),
 tensor([0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]),
 tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]),
 tensor([0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]),
 tensor([0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]),
 tensor([0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]),
 tensor([0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]),
 tensor([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])]

In [48]:
for target in testset.dataset.targets:
    test_targets.append(torch.eye(num_classes)[target])

In [51]:
test_targets[:10]

[tensor([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]),
 tensor([0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]),
 tensor([0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]),
 tensor([1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 tensor([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]),
 tensor([0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]),
 tensor([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]),
 tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]),
 tensor([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]),
 tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 1.])]

### Building the CNN

In [52]:
import torch.nn as nn
import torch.nn.functional as F

In [ ]:
class Net(nn.Module):
    def __init__(self, num_classes=num_classes, img_shape=img_shape):
        super().__init__()
        
        self.num_classes = num_classes
        self.img_shape = img_shape
        
        self.conv1 = nn.Conv2d(1, 32, 3)
        self.conv2 = nn.Conv2d(32, 64, 3)
        self.conv3 = nn.Conv2d(64, 128, 3)
        
        x = torch.randn(img_shape, img_shape).view(-1, 1, img_shape, img_shape)
        self._to_linear = None
        self.convsx(x)
        
        self.fc1 = nn.Linear(?, 128)
        self.fc2 = nn.Linear(128, num_classes)
     
    
    def convs(self, x):
        x = F.max_pool2d()

#### Credits to SentDex on Youtube - https://www.youtube.com/channel/UCfzlCWGWYyIQ0aLC5w48gBQ